export const inputCase=[

    "abcde fghij klmno pqrsta uvwxy",
    "apple banana cherry date elderberry",
    "abcd efghijklmnop qrst uvwxyz",
    "cat dog elephant giraffe horse",
    "abcdefg hijklmnop qrstuvwxy z",
    "orange lemon lime grapefruit tangerine",
    "abcd efgh ijklm nopqr",
    "bird lion tiger bear monkey",
    "alpha beta gamma delta epsilon",
    "hello world how are you todayy",
    "alpha beta gamma delta epsilon",
    "hello world how are you todayy",

    // 2
    "abcde fghij klmno pqrsta uvwxy",
    "apple banana cherry date elderberry",
    "abcd efghijklmnop qrst uvwxyz",
    "cat dog elephant giraffe horse",
    "abcdefg hijklmnop qrstuvwxy z",
    "orange lemon lime grapefruit tangerine",
    "abcd efgh ijklm nopqr",
    "bird lion tiger bear monkey",
    "alpha beta gamma delta epsilon",
    "hello world how are you todayy",
    "alpha beta gamma delta epsilon",
    "hello world how are you todayy",

    // 3
    "abcde fghij klmno pqrsta uvwxy",
    "apple banana cherry date elderberry",
    "abcd efghijklmnop qrst uvwxyz",
    "cat dog elephant giraffe horse",
    "abcdefg hijklmnop qrstuvwxy z",
    "orange lemon lime grapefruit tangerine",
    "abcd efgh ijklm nopqr",
    "bird lion tiger bear monkey",
    "alpha beta gamma delta epsilon",
    "hello world how are you todayy",
    "alpha beta gamma delta epsilon",
    "hello world how are you todayy",

    // 4
    "abcde fghij klmno pqrsta uvwxy",
    "apple banana cherry date elderberry",
    "abcd efghijklmnop qrst uvwxyz",
    "cat dog elephant giraffe horse",
    "abcdefg hijklmnop qrstuvwxy z",
    "orange lemon lime grapefruit tangerine",
    "abcd efgh ijklm nopqr",
    "bird lion tiger bear monkey",
    "alpha beta gamma delta epsilon",
    "hello world how are you todayy",
    "alpha beta gamma delta epsilon",
    "hello world how are you todayy",

    // 5
    "abcde fghij klmno pqrsta uvwxy",
    "apple banana cherry date elderberry",
    "abcd efghijklmnop qrst uvwxyz",
    "cat dog elephant giraffe horse",
    "abcdefg hijklmnop qrstuvwxy z",
    "orange lemon lime grapefruit tangerine",
    "abcd efgh ijklm nopqr",
    "bird lion tiger bear monkey",
    "alpha beta gamma delta epsilon",
    "hello world how are you todayy",
    "alpha beta gamma delta epsilon",
    "hello world how are you todayy",

    // 6
    "abcde fghij klmno pqrsta uvwxy",
    "apple banana cherry date elderberry",
    "abcd efghijklmnop qrst uvwxyz",
    "cat dog elephant giraffe horse",
    "abcdefg hijklmnop qrstuvwxy z",
    "orange lemon lime grapefruit tangerine",
    "abcd efgh ijklm nopqr",
    "bird lion tiger bear monkey",
    "alpha beta gamma delta epsilon",
    "hello world how are you todayy",
    "alpha beta gamma delta epsilon",
    "hello world how are you todayy",

    // 7
    "abcde fghij klmno pqrsta uvwxy",
    "apple banana cherry date elderberry",
    "abcd efghijklmnop qrst uvwxyz",
    "cat dog elephant giraffe horse",
    "abcdefg hijklmnop qrstuvwxy z",
    "orange lemon lime grapefruit tangerine",
    "abcd efgh ijklm nopqr",
    "bird lion tiger bear monkey",
    "alpha beta gamma delta epsilon",
    "hello world how are you todayy",
    "alpha beta gamma delta epsilon",
    "hello world how are you todayy",

    // 8
    "abcde fghij klmno pqrsta uvwxy",
    "apple banana cherry date elderberry",
    "abcd efghijklmnop qrst uvwxyz",
    "cat dog elephant giraffe horse",
    "abcdefg hijklmnop qrstuvwxy z",
    "orange lemon lime grapefruit tangerine",
    "abcd efgh ijklm nopqr",
    "bird lion tiger bear monkey",
    "alpha beta gamma delta epsilon",
    "hello world how are you todayy",
    "alpha beta gamma delta epsilon",
    "hello world how are you todayy",
]

export const outPutCase=[
    "pqrsta",
    "elderberry",
    "efghijklmnop",
    "elephant",
    "hijklmnop",
    "grapefruit",
    "ijklm",
    "monkey",
    "epsilon",
    "todayy",
    "epsilon",
    "todayy",

    // 2
    "pqrsta",
    "elderberry",
    "efghijklmnop",
    "elephant",
    "hijklmnop",
    "grapefruit",
    "ijklm",
    "monkey",
    "epsilon",
    "todayy",
    "epsilon",
    "todayy",

    // 3
    "pqrsta",
    "elderberry",
    "efghijklmnop",
    "elephant",
    "hijklmnop",
    "grapefruit",
    "ijklm",
    "monkey",
    "epsilon",
    "todayy",
    "epsilon",
    "todayy",

    // 4
    "pqrsta",
    "elderberry",
    "efghijklmnop",
    "elephant",
    "hijklmnop",
    "grapefruit",
    "ijklm",
    "monkey",
    "epsilon",
    "todayy",
    "epsilon",
    "todayy",

    // 6
    "pqrsta",
    "elderberry",
    "efghijklmnop",
    "elephant",
    "hijklmnop",
    "grapefruit",
    "ijklm",
    "monkey",
    "epsilon",
    "todayy",
    "epsilon",
    "todayy",

    // 6
    "pqrsta",
    "elderberry",
    "efghijklmnop",
    "elephant",
    "hijklmnop",
    "grapefruit",
    "ijklm",
    "monkey",
    "epsilon",
    "todayy",
    "epsilon",
    "todayy",

    // 7
    "pqrsta",
    "elderberry",
    "efghijklmnop",
    "elephant",
    "hijklmnop",
    "grapefruit",
    "ijklm",
    "monkey",
    "epsilon",
    "todayy",
    "epsilon",
    "todayy",

    // 8
    "pqrsta",
    "elderberry",
    "efghijklmnop",
    "elephant",
    "hijklmnop",
    "grapefruit",
    "ijklm",
    "monkey",
    "epsilon",
    "todayy",
    "epsilon",
    "todayy",
]
